# Generated by Django 6.0 on 2026-01-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HOD', 'Head of Department'), ('PSM', 'Project Supervisor/Manager'), ('DEAN', 'Management'), ('LECTURER', 'Lecturer')], default='ADMIN', max_length=50),
        ),
    ]
