# Generated by Django 6.0 on 2026-01-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HOD', 'HOD'), ('PSM', 'PSM'), ('DEAN', 'Management'), ('LECTURER', 'Lecturer')], default='ADMIN', max_length=50),
        ),
    ]
