# Generated by Django 6.0 on 2026-01-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskforce',
            name='department',
        ),
        migrations.AddField(
            model_name='taskforce',
            name='departments',
            field=models.ManyToManyField(related_name='task_forces', to='university.department'),
        ),
    ]
