# Generated by Django 6.0 on 2026-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_remove_taskforce_department_taskforce_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskforce',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active (Draft)'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
    ]
