# Generated by Django 6.0 on 2026-01-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_taskforce_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskforce',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
