# Generated by Django 6.0 on 2026-01-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_taskforce_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weightage', models.IntegerField(default=0)),
                ('max_weightage', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name_plural': 'Workload Settings',
            },
        ),
        migrations.AddField(
            model_name='taskforce',
            name='weightage',
            field=models.IntegerField(default=5),
        ),
    ]
