# Generated by Django 6.0 on 2026-01-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_workloadsettings_taskforce_weightage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskforce',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
    ]
