# Generated by Django 6.0 on 2026-01-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_alter_taskforce_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskforce',
            name='chairman',
        ),
        migrations.AlterField(
            model_name='taskforce',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
    ]
