# Generated by Django 6.0 on 2026-01-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_remove_taskforce_chairman_alter_taskforce_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskforce',
            name='assigned_psm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_taskforces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskforce',
            name='psm_adjusted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskforce',
            name='psm_adjustment_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskforce',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_taskforces', to=settings.AUTH_USER_MODEL),
        ),
    ]
